### PR TITLE
Added resource limits

### PR DESCRIPTION
**Pull request by breathbath**

### CODE REVIEW

**Review by Andrea-Campanella — APPROVED** [review]
pending tests

**Comment by Andrea-Campanella** [comment]
@zdw please check this within Aether Team

**Review by hwchiu — APPROVED** [review]
LGTM

**Review by kuujo — APPROVED** [review]

**Comment by breathbath** [comment]
Hey can someone merge it?

**Comment by kuujo** [comment]
@Andrea-Campanella should I release this or wait on #6?

**Pull request merged**
